### ISSUE TITLE
`OCTOSPI_CR_DQM` defined nowhere

### ISSUE THREAD

**Issue by atsju** [STMicroelectronics/stm32u5xx_hal_driver#3]
Release is 1.1.0

I only tried to compile stm32u5xx_hal_ospi.h and I get a compiler error. In fact OCTOSPI_CR_DQM is defined nowhere
There has been renamming between OCTOSPI_CR_DMM and OCTOSPI_CR_DQM ?

also RCC_CCIPR1_CLK48MSEL_0 is defined nowhere
same for RCC_CCIPR1_CLK48MSEL 

How could this release even pass any automated test tool ?

**Comment by RKOUSTM** [comment]
Hi @atsju, 

Thank you for your report. An internal tracker has been logged and a fix will be implemented and made available in the frame of a future release.

Thank you again for you report.

With regards,

**Comment by RKOUSTM** [comment]
ST Internal Reference: 126247
