### ISSUE TITLE
RCC_CCIPR1_ICLKSEL_0 and RCC_CCIPR1_ICLKSEL_1 not defined

### ISSUE THREAD

**Issue by gdobato** [STMicroelectronics/stm32u5xx_hal_driver#4]
`RCC_CCIPR1_ICLKSEL_0 and RCC_CCIPR1_ICLKSEL_1` are not not defined, so stm32u5xx_hal_rcc_ex.c faces compile errors due to missing of these definitions (and forwarded ones, like RCC_ICLK_CLKSOURCE_PLL2)

**Comment by ASELSTM** [comment]
Hi @gdobato,

Thank you for your contribution. The `RCC_CCIPR1_ICLKSEL_0` and `RCC_CCIPR1_ICLKSEL_1` are actually defined within the [CMSIS files](https://github.com/STMicroelectronics/STM32CubeU5/tree/main/Drivers/CMSIS/Device/ST/STM32U5xx/Include). 

```
#define RCC_CCIPR1_ICLKSEL_0                (0x1UL << RCC_CCIPR1_ICLKSEL_Pos)       /*!< 0x04000000 */
#define RCC_CCIPR1_ICLKSEL_1                (0x2UL << RCC_CCIPR1_ICLKSEL_Pos)       /*!< 0x08000000 */
```

Please allow me thus to close this thread.

With regards,
